-- Corelia 3NF strict proposal
-- Inspired by apps/api/prisma/schema.prisma, but not a migration of the current DB.
-- Goals:
--   * snake_case table and column names
--   * no arrays
--   * no JSON payload columns
--   * no cache/derived columns such as current_version, sync_teams_count, progress_pct
--   * no polymorphic "many nullable FK" columns; use specific link/target tables
--   * lookup/status values stored in catalog tables instead of enum-only columns

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Identity, RBAC and organizational structure
-- ============================================================

CREATE TABLE permission_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  program_id uuid NOT NULL REFERENCES programs(id) ON DELETE RESTRICT,
  category_id uuid NOT NULL REFERENCES permission_categories(id) ON DELETE RESTRICT,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE role_scopes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  role_scope_id uuid NOT NULL REFERENCES role_scopes(id) ON DELETE RESTRICT,
  rank integer NOT NULL DEFAULT 0,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE role_permissions (
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE program_roles (
  program_id uuid NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (program_id, role_id)
);

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  base_role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deactivated_at timestamptz
);

CREATE TABLE person_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  internal_contact_email text NOT NULL,
  internal_phone text,
  timezone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE skills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE person_profile_skills (
  profile_id uuid NOT NULL REFERENCES person_profiles(id) ON DELETE CASCADE,
  skill_id uuid NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
  PRIMARY KEY (profile_id, skill_id)
);

CREATE TABLE teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  description_catalog_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE team_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (team_id, user_id)
);

CREATE TABLE availability_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE availability_blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  availability_type_id uuid NOT NULL REFERENCES availability_types(id) ON DELETE RESTRICT,
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_at > start_at)
);

CREATE TABLE work_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  timezone text NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  max_active_tasks integer NOT NULL DEFAULT 5,
  period_hours_capacity numeric(8, 2) NOT NULL DEFAULT 40,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_time > start_time)
);

CREATE TABLE week_days (
  id smallint PRIMARY KEY,
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  CHECK (id BETWEEN 0 AND 6)
);

CREATE TABLE work_schedule_week_days (
  work_schedule_id uuid NOT NULL REFERENCES work_schedules(id) ON DELETE CASCADE,
  week_day_id smallint NOT NULL REFERENCES week_days(id) ON DELETE RESTRICT,
  PRIMARY KEY (work_schedule_id, week_day_id)
);

-- ============================================================
-- Projects, tasks and time tracking
-- ============================================================

CREATE TABLE project_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  description_catalog_id uuid,
  project_template_id uuid NOT NULL REFERENCES project_templates(id) ON DELETE RESTRICT,
  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  start_date date,
  estimated_end_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE project_membership_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE project_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  membership_source_id uuid NOT NULL REFERENCES project_membership_sources(id) ON DELETE RESTRICT,
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, user_id)
);

CREATE TABLE project_team_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, team_id)
);

CREATE TABLE project_member_team_sources (
  project_member_id uuid NOT NULL REFERENCES project_members(id) ON DELETE CASCADE,
  project_team_link_id uuid NOT NULL REFERENCES project_team_links(id) ON DELETE CASCADE,
  PRIMARY KEY (project_member_id, project_team_link_id)
);

CREATE TABLE project_stages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  code integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#4F7CFF',
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, code),
  UNIQUE (project_id, name),
  UNIQUE (project_id, sort_order)
);

CREATE TABLE task_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  is_terminal boolean NOT NULL DEFAULT false
);

CREATE TABLE tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  stage_id uuid REFERENCES project_stages(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  description_catalog_id uuid,
  assignee_id uuid REFERENCES users(id) ON DELETE SET NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  task_status_id uuid NOT NULL REFERENCES task_statuses(id) ON DELETE RESTRICT,
  pending_activated_at timestamptz,
  start_date date,
  due_date date,
  blocking_task_id uuid REFERENCES tasks(id) ON DELETE SET NULL,
  blocked_reason text,
  blocked_reason_catalog_id uuid,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE task_dependencies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  depends_on_task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, depends_on_task_id),
  CHECK (task_id <> depends_on_task_id)
);

CREATE TABLE task_status_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  from_task_status_id uuid REFERENCES task_statuses(id) ON DELETE RESTRICT,
  to_task_status_id uuid NOT NULL REFERENCES task_statuses(id) ON DELETE RESTRICT,
  reason text NOT NULL,
  reason_catalog_id uuid,
  changed_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE task_reassignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  previous_assignee_id uuid REFERENCES users(id) ON DELETE SET NULL,
  new_assignee_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reason text NOT NULL,
  reason_catalog_id uuid,
  reassigned_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reassigned_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE task_schedule_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  previous_start_date date,
  previous_due_date date,
  new_start_date date,
  new_due_date date,
  reason text NOT NULL,
  reason_catalog_id uuid,
  changed_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE time_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  minutes integer NOT NULL,
  note text,
  logged_at timestamptz NOT NULL DEFAULT now(),
  CHECK (minutes > 0)
);

CREATE TABLE project_details (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  description text NOT NULL,
  estimated_budget numeric(14, 2) NOT NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (estimated_budget >= 0)
);

CREATE TABLE expense_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_detail_id uuid NOT NULL REFERENCES project_details(id) ON DELETE CASCADE,
  description text NOT NULL,
  amount numeric(14, 2) NOT NULL,
  expense_date date NOT NULL,
  receipt_file_id uuid,
  expense_status_id uuid NOT NULL REFERENCES expense_statuses(id) ON DELETE RESTRICT,
  approved_by_id uuid REFERENCES users(id) ON DELETE SET NULL,
  approved_at timestamptz,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (amount >= 0)
);

-- ============================================================
-- Onboarding, offboarding and invites
-- ============================================================

CREATE TABLE onboarding_checklists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE onboarding_checklist_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  checklist_id uuid NOT NULL REFERENCES onboarding_checklists(id) ON DELETE CASCADE,
  step_key text NOT NULL,
  label text NOT NULL,
  is_required boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL,
  UNIQUE (checklist_id, step_key),
  UNIQUE (checklist_id, sort_order)
);

CREATE TABLE onboarding_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  checklist_id uuid NOT NULL REFERENCES onboarding_checklists(id) ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE onboarding_run_steps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL REFERENCES onboarding_runs(id) ON DELETE CASCADE,
  step_key text NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  UNIQUE (run_id, step_key)
);

CREATE TABLE offboarding_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  transfer_to_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  reason text NOT NULL,
  reason_catalog_id uuid,
  revoked_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  CHECK (user_id <> transfer_to_user_id)
);

CREATE TABLE internal_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  base_role_id uuid NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  resent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE signup_request_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE signup_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  message text,
  signup_request_status_id uuid NOT NULL REFERENCES signup_request_statuses(id) ON DELETE RESTRICT,
  requested_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by_id uuid REFERENCES users(id) ON DELETE SET NULL,
  decision_note text,
  invite_id uuid UNIQUE REFERENCES internal_invites(id) ON DELETE SET NULL
);

CREATE TABLE guest_invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  token_hash text NOT NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE guest_invite_projects (
  guest_invite_id uuid PRIMARY KEY REFERENCES guest_invites(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE
);

-- guest_invite_files and guest_invite_documents are defined after files/documents.

-- ============================================================
-- Messaging and meetings
-- ============================================================

CREATE TABLE channel_scopes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  channel_scope_id uuid NOT NULL REFERENCES channel_scopes(id) ON DELETE RESTRICT,
  team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (team_id IS NOT NULL AND project_id IS NULL)
    OR (team_id IS NULL AND project_id IS NOT NULL)
  )
);

CREATE TABLE channel_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (channel_id, user_id)
);

CREATE TABLE message_kinds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id uuid NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message_kind_id uuid NOT NULL REFERENCES message_kinds(id) ON DELETE RESTRICT,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE message_mentions (
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  mentioned_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (message_id, mentioned_user_id)
);

CREATE TABLE message_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  storage_path text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (size_bytes >= 0)
);

CREATE TABLE message_receipt_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE message_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message_receipt_status_id uuid NOT NULL REFERENCES message_receipt_statuses(id) ON DELETE RESTRICT,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (message_id, user_id)
);

CREATE TABLE meeting_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE meeting_call_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE meetings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  description_catalog_id uuid,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  meeting_status_id uuid NOT NULL REFERENCES meeting_statuses(id) ON DELETE RESTRICT,
  meeting_call_type_id uuid NOT NULL REFERENCES meeting_call_types(id) ON DELETE RESTRICT,
  media_room_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at > starts_at)
);

CREATE TABLE meeting_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id uuid REFERENCES roles(id) ON DELETE SET NULL,
  is_muted boolean NOT NULL DEFAULT false,
  is_camera_on boolean NOT NULL DEFAULT true,
  is_screen_sharing boolean NOT NULL DEFAULT false,
  is_speaking boolean NOT NULL DEFAULT false,
  joined_at timestamptz,
  left_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (meeting_id, user_id)
);

CREATE TABLE meeting_agenda_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  text text NOT NULL,
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (meeting_id, sort_order)
);

CREATE TABLE meeting_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE meeting_note_metadata (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_note_id uuid NOT NULL REFERENCES meeting_notes(id) ON DELETE CASCADE,
  key text NOT NULL,
  value text NOT NULL,
  UNIQUE (meeting_note_id, key)
);

CREATE TABLE meeting_agreement_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE meeting_agreements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  description_catalog_id uuid,
  meeting_agreement_status_id uuid NOT NULL REFERENCES meeting_agreement_statuses(id) ON DELETE RESTRICT,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  task_id uuid REFERENCES tasks(id) ON DELETE SET NULL,
  created_task boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE message_meetings (
  message_id uuid PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE
);

-- ============================================================
-- Notifications and calendars
-- ============================================================

CREATE TABLE calendar_providers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE external_calendar_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  calendar_provider_id uuid NOT NULL REFERENCES calendar_providers(id) ON DELETE RESTRICT,
  external_account_id text NOT NULL,
  access_token_encrypted text NOT NULL,
  refresh_token_encrypted text,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (calendar_provider_id, external_account_id)
);

CREATE TABLE external_calendar_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_id uuid NOT NULL REFERENCES external_calendar_connections(id) ON DELETE CASCADE,
  external_id text NOT NULL,
  title text NOT NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  is_read_only boolean NOT NULL DEFAULT true,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  team_id uuid REFERENCES teams(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (connection_id, external_id),
  CHECK (ends_at > starts_at)
);

CREATE TABLE notification_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE notification_channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE notification_frequencies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE notification_priorities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE notification_preferences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_event_id uuid NOT NULL REFERENCES notification_events(id) ON DELETE RESTRICT,
  notification_channel_id uuid NOT NULL REFERENCES notification_channels(id) ON DELETE RESTRICT,
  notification_frequency_id uuid NOT NULL REFERENCES notification_frequencies(id) ON DELETE RESTRICT,
  is_enabled boolean NOT NULL DEFAULT true,
  UNIQUE (user_id, notification_event_id, notification_channel_id)
);

CREATE TABLE notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_event_id uuid NOT NULL REFERENCES notification_events(id) ON DELETE RESTRICT,
  notification_channel_id uuid NOT NULL REFERENCES notification_channels(id) ON DELETE RESTRICT,
  notification_priority_id uuid NOT NULL REFERENCES notification_priorities(id) ON DELETE RESTRICT,
  group_key text,
  title text NOT NULL,
  body text NOT NULL,
  sent_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE browser_push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  expiration_time timestamptz,
  user_agent text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- Forms and requests
-- ============================================================

CREATE TABLE request_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE request_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE form_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  request_type_id uuid NOT NULL REFERENCES request_types(id) ON DELETE RESTRICT,
  request_status_id uuid NOT NULL REFERENCES request_statuses(id) ON DELETE RESTRICT,
  approver_id uuid REFERENCES users(id) ON DELETE SET NULL,
  comment text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE form_request_fields (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  form_request_id uuid NOT NULL REFERENCES form_requests(id) ON DELETE CASCADE,
  key text NOT NULL,
  value_text text NOT NULL,
  UNIQUE (form_request_id, key)
);

CREATE TABLE dynamic_forms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT false,
  allow_multiple_submissions boolean NOT NULL DEFAULT false,
  is_anonymous boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dynamic_form_question_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE dynamic_form_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL REFERENCES dynamic_forms(id) ON DELETE CASCADE,
  question_type_id uuid NOT NULL REFERENCES dynamic_form_question_types(id) ON DELETE RESTRICT,
  label text NOT NULL,
  is_required boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (form_id, sort_order)
);

CREATE TABLE dynamic_form_question_options (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL REFERENCES dynamic_form_questions(id) ON DELETE CASCADE,
  value text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL,
  UNIQUE (question_id, value),
  UNIQUE (question_id, sort_order)
);

CREATE TABLE dynamic_form_conditional_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL REFERENCES dynamic_form_questions(id) ON DELETE CASCADE,
  source_question_id uuid NOT NULL REFERENCES dynamic_form_questions(id) ON DELETE CASCADE,
  operator_key text NOT NULL,
  expected_text_value text,
  expected_number_value numeric,
  expected_date_value date,
  CHECK (
    num_nonnulls(expected_text_value, expected_number_value, expected_date_value) = 1
  )
);

CREATE TABLE dynamic_form_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL REFERENCES dynamic_forms(id) ON DELETE CASCADE,
  user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  submitted_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE dynamic_form_answers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  response_id uuid NOT NULL REFERENCES dynamic_form_responses(id) ON DELETE CASCADE,
  question_id uuid NOT NULL REFERENCES dynamic_form_questions(id) ON DELETE CASCADE,
  text_value text,
  number_value numeric,
  date_value date,
  file_id uuid,
  UNIQUE (response_id, question_id),
  CHECK (num_nonnulls(text_value, number_value, date_value, file_id) <= 1)
);

CREATE TABLE dynamic_form_answer_options (
  answer_id uuid NOT NULL REFERENCES dynamic_form_answers(id) ON DELETE CASCADE,
  option_id uuid NOT NULL REFERENCES dynamic_form_question_options(id) ON DELETE RESTRICT,
  PRIMARY KEY (answer_id, option_id)
);

-- ============================================================
-- Files and collaborative documents
-- ============================================================

CREATE TABLE folder_scopes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE folders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  folder_scope_id uuid NOT NULL REFERENCES folder_scopes(id) ON DELETE RESTRICT,
  team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  parent_id uuid REFERENCES folders(id) ON DELETE SET NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (team_id IS NOT NULL AND project_id IS NULL)
    OR (team_id IS NULL AND project_id IS NOT NULL)
  )
);

CREATE TABLE files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  storage_path text NOT NULL,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (size_bytes >= 0)
);

ALTER TABLE expenses
  ADD CONSTRAINT expenses_receipt_file_fk
  FOREIGN KEY (receipt_file_id) REFERENCES files(id) ON DELETE SET NULL;

ALTER TABLE dynamic_form_answers
  ADD CONSTRAINT dynamic_form_answers_file_fk
  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE SET NULL;

CREATE TABLE file_trash_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL UNIQUE REFERENCES files(id) ON DELETE CASCADE,
  scheduled_purge_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE storage_quota_scopes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE user_storage_quotas (
  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  bytes_limit bigint NOT NULL,
  alert_threshold_pct numeric(4, 3) NOT NULL DEFAULT 0.800,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (bytes_limit >= 0),
  CHECK (alert_threshold_pct > 0 AND alert_threshold_pct <= 1)
);

CREATE TABLE team_storage_quotas (
  team_id uuid PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
  bytes_limit bigint NOT NULL,
  alert_threshold_pct numeric(4, 3) NOT NULL DEFAULT 0.800,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (bytes_limit >= 0),
  CHECK (alert_threshold_pct > 0 AND alert_threshold_pct <= 1)
);

CREATE TABLE document_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE diagram_engines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE diagram_kinds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE collaborative_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  folder_id uuid NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
  document_type_id uuid NOT NULL REFERENCES document_types(id) ON DELETE RESTRICT,
  name text NOT NULL,
  y_doc_name text NOT NULL UNIQUE,
  diagram_engine_id uuid REFERENCES diagram_engines(id) ON DELETE SET NULL,
  diagram_kind_id uuid REFERENCES diagram_kinds(id) ON DELETE SET NULL,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  deleted_at timestamptz,
  purge_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE document_version_kinds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE collaborative_document_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE,
  version_number integer NOT NULL,
  document_version_kind_id uuid NOT NULL REFERENCES document_version_kinds(id) ON DELETE RESTRICT,
  snapshot_file_id uuid NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, version_number)
);

CREATE TABLE document_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE,
  file_id uuid NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE document_favorites (
  document_id uuid NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (document_id, user_id)
);

CREATE TABLE document_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  document_type_id uuid NOT NULL REFERENCES document_types(id) ON DELETE RESTRICT,
  name varchar(120) NOT NULL,
  description varchar(500),
  snapshot_file_id uuid NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE document_collab_session_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE document_collab_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE,
  room_name text NOT NULL,
  document_collab_session_status_id uuid NOT NULL REFERENCES document_collab_session_statuses(id) ON DELETE RESTRICT,
  revision integer NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz
);

CREATE TABLE document_collab_participant_statuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE document_collab_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES document_collab_sessions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id text NOT NULL,
  document_collab_participant_status_id uuid NOT NULL REFERENCES document_collab_participant_statuses(id) ON DELETE RESTRICT,
  joined_at timestamptz NOT NULL DEFAULT now(),
  left_at timestamptz,
  last_heartbeat_at timestamptz,
  UNIQUE (session_id, user_id, client_id)
);

CREATE TABLE document_collab_event_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE document_collab_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES document_collab_sessions(id) ON DELETE CASCADE,
  user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  client_id text,
  document_collab_event_type_id uuid NOT NULL REFERENCES document_collab_event_types(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE document_collab_event_fields (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES document_collab_events(id) ON DELETE CASCADE,
  key text NOT NULL,
  value_text text NOT NULL,
  UNIQUE (event_id, key)
);

CREATE TABLE guest_invite_files (
  guest_invite_id uuid PRIMARY KEY REFERENCES guest_invites(id) ON DELETE CASCADE,
  file_id uuid NOT NULL REFERENCES files(id) ON DELETE CASCADE
);

CREATE TABLE guest_invite_documents (
  guest_invite_id uuid PRIMARY KEY REFERENCES guest_invites(id) ON DELETE CASCADE,
  document_id uuid NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE
);

-- ============================================================
-- Announcements, decisions, objectives and automations
-- ============================================================

CREATE TABLE announcement_schedule_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL,
  is_all_company boolean NOT NULL DEFAULT false,
  announcement_schedule_type_id uuid NOT NULL REFERENCES announcement_schedule_types(id) ON DELETE RESTRICT,
  starts_at timestamptz,
  expires_at timestamptz NOT NULL,
  recurring_month smallint,
  recurring_day smallint,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (recurring_month IS NULL OR recurring_month BETWEEN 1 AND 12),
  CHECK (recurring_day IS NULL OR recurring_day BETWEEN 1 AND 31)
);

CREATE TABLE announcement_teams (
  announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  PRIMARY KEY (announcement_id, team_id)
);

CREATE TABLE announcement_users (
  announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (announcement_id, user_id)
);

CREATE TABLE decision_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  description_catalog_id uuid,
  author_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE decision_note_user_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, user_id)
);

CREATE TABLE decision_note_project_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, project_id)
);

CREATE TABLE decision_note_task_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, task_id)
);

CREATE TABLE decision_note_meeting_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  meeting_id uuid NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, meeting_id)
);

CREATE TABLE decision_note_message_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, message_id)
);

CREATE TABLE decision_note_file_links (
  decision_note_id uuid NOT NULL REFERENCES decision_notes(id) ON DELETE CASCADE,
  file_id uuid NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  PRIMARY KEY (decision_note_id, file_id)
);

CREATE TABLE objective_scopes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE objectives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  objective_scope_id uuid NOT NULL REFERENCES objective_scopes(id) ON DELETE RESTRICT,
  team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  description_catalog_id uuid,
  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (team_id IS NOT NULL AND project_id IS NULL)
    OR (team_id IS NULL AND project_id IS NOT NULL)
  )
);

CREATE TABLE objective_tasks (
  objective_id uuid NOT NULL REFERENCES objectives(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  PRIMARY KEY (objective_id, task_id)
);

CREATE TABLE automation_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE automation_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE automation_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name text NOT NULL,
  automation_event_id uuid NOT NULL REFERENCES automation_events(id) ON DELETE RESTRICT,
  automation_action_id uuid NOT NULL REFERENCES automation_actions(id) ON DELETE RESTRICT,
  is_enabled boolean NOT NULL DEFAULT true,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE automation_rule_parameters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  automation_rule_id uuid NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE,
  key text NOT NULL,
  value_text text NOT NULL,
  UNIQUE (automation_rule_id, key)
);

-- ============================================================
-- Integrations, import and audit
-- ============================================================

CREATE TABLE webhook_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE webhook_endpoints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  url text NOT NULL,
  webhook_event_id uuid NOT NULL REFERENCES webhook_events(id) ON DELETE RESTRICT,
  secret text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint_id uuid NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
  status_code integer,
  is_success boolean NOT NULL DEFAULT false,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_delivery_fields (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  webhook_delivery_id uuid NOT NULL REFERENCES webhook_deliveries(id) ON DELETE CASCADE,
  key text NOT NULL,
  value_text text NOT NULL,
  UNIQUE (webhook_delivery_id, key)
);

CREATE TABLE import_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE import_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  import_source_id uuid NOT NULL REFERENCES import_sources(id) ON DELETE RESTRICT,
  file_name text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  is_success boolean NOT NULL DEFAULT false,
  created_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE import_errors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES import_jobs(id) ON DELETE CASCADE,
  row_number integer NOT NULL,
  field_name text NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE refresh_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  rotated_from_id uuid REFERENCES refresh_tokens(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_action_id uuid NOT NULL REFERENCES audit_actions(id) ON DELETE RESTRICT,
  actor_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  reason text,
  reason_catalog_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_log_field_changes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_log_id uuid NOT NULL REFERENCES audit_logs(id) ON DELETE CASCADE,
  field_name text NOT NULL,
  previous_value text,
  new_value text,
  UNIQUE (audit_log_id, field_name)
);

CREATE TABLE audit_log_user_targets (
  audit_log_id uuid NOT NULL REFERENCES audit_logs(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (audit_log_id, user_id)
);

CREATE TABLE audit_log_project_targets (
  audit_log_id uuid NOT NULL REFERENCES audit_logs(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  PRIMARY KEY (audit_log_id, project_id)
);

CREATE TABLE audit_log_task_targets (
  audit_log_id uuid NOT NULL REFERENCES audit_logs(id) ON DELETE CASCADE,
  task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  PRIMARY KEY (audit_log_id, task_id)
);

CREATE TABLE audit_log_file_targets (
  audit_log_id uuid NOT NULL REFERENCES audit_logs(id) ON DELETE CASCADE,
  file_id uuid NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  PRIMARY KEY (audit_log_id, file_id)
);

-- ============================================================
-- Code catalogs
-- ============================================================

CREATE TABLE code_catalog_domains (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  display_name text NOT NULL
);

CREATE TABLE code_catalog_fields (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_id uuid NOT NULL REFERENCES code_catalog_domains(id) ON DELETE CASCADE,
  key text NOT NULL,
  display_name text NOT NULL,
  UNIQUE (domain_id, key)
);

CREATE TABLE code_catalog_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  field_id uuid NOT NULL REFERENCES code_catalog_fields(id) ON DELETE CASCADE,
  code integer GENERATED BY DEFAULT AS IDENTITY,
  key text NOT NULL,
  label text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (field_id, code),
  UNIQUE (field_id, key)
);

ALTER TABLE teams
  ADD CONSTRAINT teams_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE projects
  ADD CONSTRAINT projects_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE tasks
  ADD CONSTRAINT tasks_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL,
  ADD CONSTRAINT tasks_blocked_reason_catalog_fk
  FOREIGN KEY (blocked_reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE task_status_history
  ADD CONSTRAINT task_status_history_reason_catalog_fk
  FOREIGN KEY (reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE task_reassignments
  ADD CONSTRAINT task_reassignments_reason_catalog_fk
  FOREIGN KEY (reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE task_schedule_history
  ADD CONSTRAINT task_schedule_history_reason_catalog_fk
  FOREIGN KEY (reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE offboarding_records
  ADD CONSTRAINT offboarding_records_reason_catalog_fk
  FOREIGN KEY (reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE meetings
  ADD CONSTRAINT meetings_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE meeting_agreements
  ADD CONSTRAINT meeting_agreements_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE decision_notes
  ADD CONSTRAINT decision_notes_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE objectives
  ADD CONSTRAINT objectives_description_catalog_fk
  FOREIGN KEY (description_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

ALTER TABLE audit_logs
  ADD CONSTRAINT audit_logs_reason_catalog_fk
  FOREIGN KEY (reason_catalog_id) REFERENCES code_catalog_entries(id) ON DELETE SET NULL;

-- ============================================================
-- Singleton operational settings
-- ============================================================

CREATE TABLE maintenance_mode (
  id boolean PRIMARY KEY DEFAULT true,
  is_enabled boolean NOT NULL DEFAULT false,
  message text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (id)
);

CREATE TABLE frontend_settings (
  id boolean PRIMARY KEY DEFAULT true,
  organization_name text NOT NULL,
  task_status_color_pending text NOT NULL,
  task_status_color_in_review text NOT NULL,
  task_status_color_completed text NOT NULL,
  instant_call_expiry_hours integer NOT NULL DEFAULT 24,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (id),
  CHECK (instant_call_expiry_hours > 0)
);

-- ============================================================
-- Helpful indexes
-- ============================================================

CREATE INDEX permissions_program_id_idx ON permissions(program_id);
CREATE INDEX permissions_category_id_idx ON permissions(category_id);
CREATE INDEX users_base_role_id_idx ON users(base_role_id);
CREATE INDEX team_members_user_id_idx ON team_members(user_id);
CREATE INDEX project_members_user_id_idx ON project_members(user_id);
CREATE INDEX project_members_role_id_idx ON project_members(role_id);
CREATE INDEX tasks_project_id_idx ON tasks(project_id);
CREATE INDEX tasks_assignee_id_idx ON tasks(assignee_id);
CREATE INDEX tasks_status_id_idx ON tasks(task_status_id);
CREATE INDEX time_entries_user_id_idx ON time_entries(user_id);
CREATE INDEX time_entries_task_id_idx ON time_entries(task_id);
CREATE INDEX messages_channel_id_idx ON messages(channel_id);
CREATE INDEX messages_author_id_idx ON messages(author_id);
CREATE INDEX meetings_project_id_idx ON meetings(project_id);
CREATE INDEX meetings_team_id_idx ON meetings(team_id);
CREATE INDEX files_folder_id_idx ON files(folder_id);
CREATE INDEX files_owner_id_idx ON files(owner_id);
CREATE INDEX collaborative_documents_project_id_idx ON collaborative_documents(project_id);
CREATE INDEX collaborative_document_versions_document_id_idx ON collaborative_document_versions(document_id, version_number DESC);
CREATE INDEX notifications_user_id_idx ON notifications(user_id);
CREATE INDEX audit_logs_created_at_idx ON audit_logs(created_at);
